version: "3.7"

services:
    core:
        container_name: core
        ports:
            - 8000:8000
        build:
            context: auth_api/python
        volumes:
            - ./auth_api/python:/core
