version: "3.7"

services:
  core:
    container_name: core
    image: nietzscheson/wize-cristian-angulo:latest
    ports:
      - 8000:8000
    build:
      context: auth_api/python
      cache_from: 
        - nietzscheson/wize-cristian-angulo:latest
      args:
        - DATABASE_HOST=${DATABASE_HOST}
        - DATABASE_USER=${DATABASE_USER}
        - DATABASE_PASS=${DATABASE_PASS}
        - DATABASE_NAME=${DATABASE_NAME}
        - DATABASE_PORT=${DATABASE_PORT}
        - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ./auth_api/python:/core
      